### ISSUE TITLE
Error when try to nest not nested properties

### ISSUE THREAD

**Issue by samuelmanzanera** [fredsh/revampjs#1]
I notice a issue , but it's more bounding issue.

Using this source:

```js
const sourceObject = {
  a: 42,
  b: 'hello',
  c: 'world',
  d: '!',
  e: {
    f: 'nested value'
  }
}
```

When you call the extract method and specify nested pattern on not object property
```js
const extracted = revamp.extract(sourceObject, {
	none: 'a.b'
})
```

this error message appears: 
**TypeError: Cannot use 'in' operator to search for 'b' in 42**

I think i just need to check if the pattern match an object for nested case and reject the transformation or display an error message.

But it's good anyway :+1

**Comment by fredsh** [comment]
@samuelmanzanera thanks for catching this one. I added a test case that reproduce this issue and fixed it.
Please feel free to reopen if that is not working as you expect (intended behaviour is to return `undefined` for any falsy key).
